### PR TITLE
fix(kmodal): add focus trap activation delay

### LINKED ISSUE #946: Regression in v8.8.0: focus-trap throws error in tests
With the upgrade to Kongponents v8.8.0 (#940), the tests in https://github.com/kumahq/kuma-gui start to fail. Specifically https://github.com/kumahq/kuma-gui/blob/56e95963525e4df0dfc714e577d9d99fffb80255/src/app/notification-manager/components/TracingNotification.spec.ts fails. It tests a component using `KModal`.

**Error**:

```
Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at p (/home/phil/kong/kuma-gui/node_modules/@kong/kongponents/dist/kongponents.umd.js:459:3525)
    at Object.activate (/home/phil/kong/kuma-gui/node_modules/@kong/kongponents/dist/kongponents.umd.js:459:6214)
    at Proxy.activate (/home/phil/kong/kuma-gui/node_modules/@kong/kongponents/dist/kongponents.umd.js:463:1517)
    at /home/phil/kong/kuma-gui/node_modules/@kong/kongponents/dist/kongponents.umd.js:463:3282
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It’s unclear to me why this happens because as far as I can tell, our use of `KModal` always includes severeal interactive elements (e.g. one in the form of a close button rendered into the `footer-content` slot).

It looks like `KModal` does try to take into account that its `isVisible` prop is going to be activated before the slot content had time to render.

For now, I don’t know what we can possibly do on our end to fix our tests so I’m filing a bug report here.

**Steps to reproduce**:

```sh
git clone https://github.com/kumahq/kuma-gui.git
yarn install
yarn test src/app/notification-manager/components/NotificationManager.spec.ts

# Updates Kongponents
yarn upgrade @kong/kongponents
yarn test src/app/notification-manager/components/NotificationManager.spec.ts
```

### PR DESCRIPTION
**Pull request by adamdehaven**
# Summary

Add a delay for focus trap activation to ensure the focused element doesn't capture the event that caused the activation. Resolves #946.

## PR Checklist

* [X] Does not introduce dependencies
* [X] **Functional:** all changes do not break existing APIs and if so, bump major version.
* [X] **Tests pass:** check the output of yarn test
* [X] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
* [X] **Framework style:** abides by the essential rules in Vue's style guide
* [X] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs, debugger), or leftover comments
* [ ] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

### CODE REVIEW

File: src/components/KModal/KModal.vue [hunk 1]
```diff
@@ -253,16 +253,27 @@ export default defineComponent({
...
+    watch(() => props.isVisible, async (isVisible) => {
+      if (isVisible) {
+        await toggleFocusTrap(true)
+      } else {
+        await toggleFocusTrap(false)
+      }
+    }, { immediate: true })
 
-    onMounted(() => {
+    onMounted(async () => {
```
Comment (kleinfreund) [inline src/components/KModal/KModal.vue:276]: **Suggestion**: remnant

```suggestion
    onMounted(() => {
```

File: src/components/KModal/KModal.vue [hunk 2]
```diff
@@ -271,7 +282,7 @@ export default defineComponent({
       }
     })
 
-    onUnmounted(() => {
+    onUnmounted(async () => {
```
Comment (kleinfreund) [inline src/components/KModal/KModal.vue:285]: **Suggestion**: remnant

```suggestion
    onUnmounted(() => {
```

**Review by kleinfreund — APPROVED** [review]

File: src/components/KModal/KModal.vue (hunk 1 above)
Comment (adamdehaven) [reply src/components/KModal/KModal.vue]: Done

File: src/components/KModal/KModal.vue (hunk 2 above)
Comment (adamdehaven) [reply src/components/KModal/KModal.vue]: Done

**Review by kleinfreund — APPROVED** [review]
